DIS = ['Dhaka ', 'Brahmanbaria', 'Bagherhat', 'Bandarban', 'Barguna', 'Barishal', 'Bhola', 'Bogra', 'C. Nawabganj', 'Chandpur', 'Chittagong', 'Chuadanga ', 'Comilla', "Cox's Bazar", 'Dinajpur', 'Faridpur', 'Feni', 'Gaibandha', 'Gazipur', 'Gopalganj', 'Habiganj', 'Jamalpur', 'Jessore', 'Jhalokathi', 'Jhenaidah ', 'Joypurhat ', 'Khagrachari ', 'Khulna', 'Kishoreganj ', 'Kurigram', 'Kushtia ', 'Lalmonirhat', 'Laxmipur', 'Madaripur ', 'Magura', 'Manikganj', 'Meherpur', 'Moulvibazar', 'Munshiganj', 'Mymensingh', 'Naogaon', 'Narail', 'Narayanganj', 'Narshingdi', 'Natore ', 'Netrakona', 'Nilphamari ', 'Noakhali', 'Pabna ', 'Panchagarh', 'Patuakhali', 'Perojpur', 'Rajbari', 'Rajshahi', 'Rangamati', 'Rangpur ', 'Satkhira', 'Serajganj', 'Shariatpur', 'Sherpur', 'Sunamganj', 'Sylhet ', 'Tangail', 'Thakurgaon']

DISTRICTS = (
    ('Dhaka', 'Dhaka'),
    ('Brahmanbaria', 'Brahmanbaria'),
    ('Bagherhat', 'Bagherhat'),
    ('Bandarban', 'Bandarban'),
    ('Barguna', 'Barguna'),
    ('Barishal', 'Barishal'),
    ('Bhola', 'Bhola'),
    ('Bogra', 'Bogra'),
    ('C. Nawabganj', 'C. Nawabganj'),
    ('Chandpur', 'Chandpur'),
    ('Chittagong', 'Chittagong'),
    ('Chuadanga', 'Chuadanga'),
    ('Comilla', 'Comilla'),
    ("Cox's Bazar", "Cox's Bazar"),
    ('Dinajpur', 'Dinajpur'),
    ('Faridpur', 'Faridpur'),
    ('Feni', 'Feni'),
    ('Gaibandha', 'Gaibandha'),
    ('Gazipur', 'Gazipur'),
    ('Gopalganj', 'Gopalganj'),
    ('Habiganj', 'Habiganj'),
    ('Jamalpur', 'Jamalpur'),
    ('Jessore', 'Jessore'),
    ('Jhalokathi', 'Jhalokathi'),
    ('Jhenaidah', 'Jhenaidah'),
    ('Joypurhat', 'Joypurhat'),
    ('Khagrachari', 'Khagrachari'),
    ('Khulna', 'Khulna'),
    ('Kishoreganj', 'Kishoreganj'),
    ('Kurigram', 'Kurigram'),
    ('Kushtia', 'Kushtia'),
    ('Lalmonirhat', 'Lalmonirhat'),
    ('Laxmipur', 'Laxmipur'),
    ('Madaripur', 'Madaripur'),
    ('Magura', 'Magura'),
    ('Manikganj', 'Manikganj'),
    ('Meherpur', 'Meherpur'),
    ('Moulvibazar', 'Moulvibazar'),
    ('Munshiganj', 'Munshiganj'),
    ('Mymensingh', 'Mymensingh'),
    ('Naogaon', 'Naogaon'),
    ('Narail', 'Narail'),
    ('Narayanganj', 'Narayanganj'),
    ('Narshingdi', 'Narshingdi'),
    ('Natore', 'Natore'),
    ('Netrakona', 'Netrakona'),
    ('Nilphamari', 'Nilphamari'),
    ('Noakhali', 'Noakhali'),
    ('Pabna', 'Pabna'),
    ('Panchagarh', 'Panchagarh'),
    ('Patuakhali', 'Patuakhali'),
    ('Perojpur', 'Perojpur'),
    ('Rajbari', 'Rajbari'),
    ('Rajshahi', 'Rajshahi'),
    ('Rangamati', 'Rangamati'),
    ('Rangpur', 'Rangpur'),
    ('Satkhira', 'Satkhira'),
    ('Serajganj', 'Serajganj'),
    ('Shariatpur', 'Shariatpur'),
    ('Sherpur', 'Sherpur'),
    ('Sunamganj', 'Sunamganj'),
    ('Sylhet', 'Sylhet'),
    ('Tangail', 'Tangail'),
    ('Thakurgaon', 'Thakurgaon'),
)