# Generated by Django 4.2.4 on 2023-08-28 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ambulance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Enter ambulance company's name -> John Doe", max_length=100)),
                ('contact_info', models.CharField(help_text="Enter ambulance company's contact info -> +92 123 4567890", max_length=100)),
                ('district', models.CharField(choices=[('Dhaka', 'Dhaka'), ('Brahmanbaria', 'Brahmanbaria'), ('Bagherhat', 'Bagherhat'), ('Bandarban', 'Bandarban'), ('Barguna', 'Barguna'), ('Barishal', 'Barishal'), ('Bhola', 'Bhola'), ('Bogra', 'Bogra'), ('C. Nawabganj', 'C. Nawabganj'), ('Chandpur', 'Chandpur'), ('Chittagong', 'Chittagong'), ('Chuadanga', 'Chuadanga'), ('Comilla', 'Comilla'), ("Cox's Bazar", "Cox's Bazar"), ('Dinajpur', 'Dinajpur'), ('Faridpur', 'Faridpur'), ('Feni', 'Feni'), ('Gaibandha', 'Gaibandha'), ('Gazipur', 'Gazipur'), ('Gopalganj', 'Gopalganj'), ('Habiganj', 'Habiganj'), ('Jamalpur', 'Jamalpur'), ('Jessore', 'Jessore'), ('Jhalokathi', 'Jhalokathi'), ('Jhenaidah', 'Jhenaidah'), ('Joypurhat', 'Joypurhat'), ('Khagrachari', 'Khagrachari'), ('Khulna', 'Khulna'), ('Kishoreganj', 'Kishoreganj'), ('Kurigram', 'Kurigram'), ('Kushtia', 'Kushtia'), ('Lalmonirhat', 'Lalmonirhat'), ('Laxmipur', 'Laxmipur'), ('Madaripur', 'Madaripur'), ('Magura', 'Magura'), ('Manikganj', 'Manikganj'), ('Meherpur', 'Meherpur'), ('Moulvibazar', 'Moulvibazar'), ('Munshiganj', 'Munshiganj'), ('Mymensingh', 'Mymensingh'), ('Naogaon', 'Naogaon'), ('Narail', 'Narail'), ('Narayanganj', 'Narayanganj'), ('Narshingdi', 'Narshingdi'), ('Natore', 'Natore'), ('Netrakona', 'Netrakona'), ('Nilphamari', 'Nilphamari'), ('Noakhali', 'Noakhali'), ('Pabna', 'Pabna'), ('Panchagarh', 'Panchagarh'), ('Patuakhali', 'Patuakhali'), ('Perojpur', 'Perojpur'), ('Rajbari', 'Rajbari'), ('Rajshahi', 'Rajshahi'), ('Rangamati', 'Rangamati'), ('Rangpur', 'Rangpur'), ('Satkhira', 'Satkhira'), ('Serajganj', 'Serajganj'), ('Shariatpur', 'Shariatpur'), ('Sherpur', 'Sherpur'), ('Sunamganj', 'Sunamganj'), ('Sylhet', 'Sylhet'), ('Tangail', 'Tangail'), ('Thakurgaon', 'Thakurgaon')], help_text="Enter ambulance company's district -> Dhaka", max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='BloodDonor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Enter donor's name -> John Doe", max_length=100)),
                ('blood_group', models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], help_text="Enter donor's blood group -> A+", max_length=10)),
                ('location', models.CharField(help_text="Enter donor's location -> Karachi, Pakistan", max_length=100)),
                ('contact_info', models.CharField(help_text="Enter donor's contact info -> +92 123 4567890", max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Enter doctor's name -> John Doe", max_length=100)),
                ('speciality', models.CharField(help_text="Enter doctor's speciality -> Cardiologist", max_length=200)),
                ('degrees_earned', models.CharField(help_text="Enter doctor's degrees earned -> MBBS, MCPS, FCPS (Radiotherapy), FRCP (Edin), PhD (Oncology)", max_length=200)),
                ('position', models.CharField(blank=True, help_text="Enter doctor's position -> Professor of Oncology", max_length=200, null=True)),
                ('location', models.CharField(help_text="Enter doctor's location -> Karachi, Pakistan", max_length=100)),
                ('visiting_place', models.CharField(blank=True, help_text="Enter doctor's visiting place -> Aga Khan University Hospital", max_length=100, null=True)),
                ('visiting_hours', models.CharField(blank=True, help_text="Enter doctor's visiting hours -> 9:00 AM - 5:00 PM", max_length=100, null=True)),
                ('contact_info', models.CharField(help_text="Enter doctor's contact info -> +92 123 4567890", max_length=100)),
                ('img', models.ImageField(blank=True, null=True, upload_to='doctor_pics/')),
            ],
        ),
    ]
